-- LOGIN WITH ADMINUSER AND CREATE THE OWN SCHEMA
CREATE SCHEMA tienda AUTHORIZATION adminuser;

-- ESTABLISH BY DEFAULT PATH TO TIENDA
SET search_path TO tienda;

-- SET CLIENT INSERT IN UTF8 METACHARSET
SET client_encoding = 'UTF8';
